function InitialItems(){
	//AddItem(ITEM_BASIC_ATTACK, 100)
	AddItem(ITEM_BASIC_JUMP, 100)
	//AddItem(ITEM_BASIC_DASH, 100)
	//AddItem(ITEM_BASIC_ARROW, 30)
	//AddItem(ITEM_BASIC_BOW, 100)
	AddItem(ITEM_WALL_BOOTS, 100)
	//AddItem(ITEM_BASIC_BOMB, 30)
}